# Site settings
title: Bastián Venegas
description: 'Business Card Page'
url: 'https://www.zuehlke.cloud'
baseurl: ''
profilepic: '/images/Bastian.jpeg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Bastián Venegas'
  email: batian.venegas.morales@gmail.com
  mastodon: tzuehlke@mstdn.social
  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  BastianSec
  linkedin_username:  thomas-zühlke-889182165
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
